site_name: FLEET MDE Kundenportal
site_url: https://harzmann.github.io/fleet_mde_doc/
repo_url: https://github.com/harzmann/fleet_mde_doc
theme:
  name: material
  language: de
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
nav:
  - Start: index.md
  - Installation: installation.md
  - Änderungen: changelog.md
copyright: Copyright eh-systemhaus 2026
markdown_extensions:
  - admonition
  - toc:
      permalink: true

